# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Door Selection Game
import random
print("Welcome to the door selelction game!")
print("Choose a door : 1,2,3")
door = int(input("Select your choice:"))
outcomes = ["Monster Ate you!", "You win Gold!", "Snake Bite!"]
result = random.choice(outcomes)
print(result)