# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Random Adventure Game
import random
print("Welcome to the game")
print("Choose an action: fight, run or hide")

action = input("What will you choose ? ").lower()
if action == "fight":
  outcome = random.choice(["You defeated the dragon!", "The dragon defeated you!", "Game Over!"])
  print(outcome)
elif action == "run":

  outcome = random.choice(["You escaped safely!","You tripped and got caught","The monster found you! Game Over!"])
  print(outcome)

elif action == "hide":
  outcome = ramdom.choice(["You stayed hidden and survived!", "The monster found you! Game over!"])
  print(outcome)
else:
  print("Invalid choice! Please choose fight,run or hide")

