# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Dice rolling game
import random
print("Welcome to the dice rolling game")

roll = random.randint(1,6)
print(f"YOu rolled:{roll}")
if roll == 6:
    print("You Win!")
elif roll == 1:
    print("Bad luck!")
else:
    print("Try Again")

